name: example
description: A project used to demo the Todo Reporter
version: 1.0.0+2

environment:
  sdk: ">=2.9.0 <3.0.0"

dependencies:
  todo_reporter:
    path: ../todo_reporter/

dev_dependencies:
  build_runner: ^1.0.0
  todo_reporter_generator:
    path: ../todo_reporter_generator/
