name: todo_reporter
description: Keep track of all your TODOs.
version: 1.0.0+1
author: Jorge Coca <jcocaramos@gmail.com>
homepage: https://github.com/jorgecoca/todo_reporter.dart

environment:
  sdk: ">=2.9.0 <3.0.0"

dev_dependencies:
  test: ^1.0.0