name: todo_reporter_generator
description: A new flutter package project.
version: 1.0.0+1
author: Jorge Coca <jcocaramos@gmail.com>
homepage: https://github.com/jorgecoca/todo_reporter.dart

environment:
  sdk: ">=2.7.0 <3.0.0"

dependencies:
  analyzer: "0.39.14" # Pin the analyzer version to work around generatiuon failure
  build: ^1.3.0
  build_config: ^0.4.0
  source_gen: ^0.9.0
  todo_reporter:
    path: ../todo_reporter/
  
dev_dependencies:
  test: ^1.6.0
