name: todo_reporter_generator
description: A new flutter package project.
version: 1.0.0+1
author: Jorge Coca <jcocaramos@gmail.com>
homepage: https://github.com/jorgecoca/todo_reporter.dart

environment:
  sdk: ">=2.12.0 <3.0.0"

dependencies:
  analyzer: ^2.7.0 # Pin the analyzer version to work around generatiuon failure
  build: ^2.1.1
  build_config: ^1.0.0
  source_gen: ^1.1.1
  todo_reporter:
    path: ../todo_reporter/
  
dev_dependencies:
  test: ^1.6.0
